sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge se-methods
  
  - docker build -t se_methods .
  - docker run --network se-methods se_methods